version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Customer_portal
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: customer_portal_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_portal
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

